### ISSUE TITLE
Cant select my own department

### ISSUE THREAD

**Issue by JoepKleinmeulman** [datawisdomStudio/zoho-desk#2]
I seem to have an error. I tried this out this weekend and it worked fine, however now, im unable to select my ZOHO departments, only see a different one.

**Comment by datawisdomStudio** [comment]
Thank you, we will check it immediately and update the status.

Sorry for the inconvenience.

**Comment by datawisdomStudio** [comment]
We have updated the version to fix the bug.

To apply the change, please locate the data source and edit it. 

When you enter it, it will prompt you to re-authenticate against Zoho and the configuration will appear correctly.

Thank you very much for your time and sorry for the inconvenience.
